export const jobs = [
  {
    id: 1,
    company: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    duration: "3 months",
    role: "Senior UI/UX Designer",
    tags: ["Full Time", "Design"],
    rate: "120/hr",
    location: "Mumbai, India",
  },
  {
    id: 2,
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    duration: "6 months",
    role: "Frontend React Developer",
    tags: ["Remote", "React", "JavaScript"],
    rate: "150/hr",
    location: "Bangalore, India",
  },
  {
    id: 3,
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    duration: "1 year",
    role: "Backend Node Developer",
    tags: ["Backend", "NodeJS"],
    rate: "140/hr",
    location: "Hyderabad, India",
  },
  {
    id: 4,
    company: "Netflix",
    logo: "https://logo.clearbit.com/netflix.com",
    duration: "9 months",
    role: "Product Designer",
    tags: ["UI/UX", "Creative"],
    rate: "160/hr",
    location: "Remote",
  },
  {
    id: 5,
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    duration: "4 months",
    role: "Full Stack Developer",
    tags: ["Full Stack", "JavaScript"],
    rate: "180/hr",
    location: "Delhi, India",
  },
  {
    id: 6,
    company: "Apple",
    logo: "https://logo.clearbit.com/apple.com",
    duration: "8 months",
    role: "iOS App Developer",
    tags: ["Swift", "Mobile"],
    rate: "200/hr",
    location: "Pune, India",
  },
  {
    id: 7,
    company: "Tesla",
    logo: "https://logo.clearbit.com/tesla.com",
    duration: "5 months",
    role: "AI Engineer",
    tags: ["AI", "Python"],
    rate: "220/hr",
    location: "Remote",
  },
  {
    id: 8,
    company: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    duration: "6 months",
    role: "Frontend Web Designer",
    tags: ["CSS", "Figma"],
    rate: "130/hr",
    location: "Gurgaon, India",
  },
  {
    id: 9,
    company: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    duration: "10 months",
    role: "UI Engineer",
    tags: ["UI", "JavaScript"],
    rate: "145/hr",
    location: "Remote",
  },
  {
    id: 10,
    company: "Flipkart",
    logo: "https://logo.clearbit.com/flipkart.com",
    duration: "7 months",
    role: "E-Commerce Developer",
    tags: ["React", "NodeJS"],
    rate: "135/hr",
    location: "Chennai, India",
  }
];
